language: python

python:
  - "2.7"
  - "3.3"

env:
  - DJANGO_VERSION=Django==1.4.2
  - DJANGO_VERSION=Django==1.4.3
  - DJANGO_VERSION=Django==1.4.4
  - DJANGO_VERSION=Django==1.4.5
  - DJANGO_VERSION=Django==1.4.6
  - DJANGO_VERSION=Django==1.4.7
  - DJANGO_VERSION=Django==1.4.8
  - DJANGO_VERSION=Django==1.4.9
  - DJANGO_VERSION=Django==1.4.10
  - DJANGO_VERSION=Django==1.5
  - DJANGO_VERSION=Django==1.5.1
  - DJANGO_VERSION=Django==1.5.2
  - DJANGO_VERSION=Django==1.5.3
  - DJANGO_VERSION=Django==1.5.4
  - DJANGO_VERSION=Django==1.5.5
  - DJANGO_VERSION=Django==1.5.6
  - DJANGO_VERSION=Django==1.5.7
  - DJANGO_VERSION=Django==1.6
  - DJANGO_VERSION=Django==1.6.1
  - DJANGO_VERSION=Django==1.6.2
  - DJANGO_VERSION=Django==1.6.3
  - DJANGO_VERSION=Django==1.6.4
  - DJANGO_VERSION=Django==1.6.5

# command to install dependencies
install:
  - pip install --use-mirrors $DJANGO_VERSION

# command to run tests

script:
  - python runtests.py

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.2
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.3
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.4
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.5
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.6
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.7
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.8
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.9
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.10
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.2
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.3
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.4
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.5
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.6
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.7
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.8
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.9
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.10

